version: "3.7"
#--------------------------------------------------
# SERVICES
#--------------------------------------------------
services:
  #--------------------------------------------------
  # APPLICATION
  #--------------------------------------------------
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_LOG_TO_STDOUT
      - DATABASE_URL=postgres://postgres:CBZCZF8L9Fh82gxbvZXgXrbvs7rsqzqkCQ2rnjvB@postgres:5432/voyager
      - REDIS_URL=redis://redis:6379/0
      - PORT=3500
      - RUBY_DEBUG_ENABLE=0
      - RUBY_DEBUG_OPEN=true
      - RUBY_DEBUG_PORT=35000
      - RUBY_DEBUG_HOST=0.0.0.0
      - RUBY_DEBUG_SKIP_BP=true
    ports:
      - 3500:3500
      - 35000:35000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - vendor-data:/vendor
    networks:
      - service-net
      - backend-net

  #--------------------------------------------------
  # UTILITY SERVICES
  #--------------------------------------------------
  mail-catcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - service-net
      - backend-net

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=CBZCZF8L9Fh82gxbvZXgXrbvs7rsqzqkCQ2rnjvB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - backend-net

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks: 
      - backend-net

#--------------------------------------------------
# VOLUMES
#--------------------------------------------------
volumes:
  postgres-data:
  redis-data:
  vendor-data:

#--------------------------------------------------
# NETWORKS
#--------------------------------------------------
networks:
  service-net:
    external: true
  backend-net:
    external: true
